version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - run:
          name: save-cache-checksum
          command: find -name "package.json" | xargs cat > /tmp/cache-checksum

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/tmp/cache-checksum" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: bootstrap
          command: yarn

      - run:
          name: lint
          command: yarn lint

      - run:
          name: test
          command: |
            yarn test

      - store_artifacts:
          path: ./packages/core/test-results.xml
          prefix: core

      - store_artifacts:
          path: ./packages/task-manager/test-results.xml
          prefix: task-manager

      - store_artifacts:
          path: ./packages/history/test-results.xml
          prefix: history

      - store_test_results:
          path: ./junit

workflows:
  version: 2
  build-all:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
