version: 2
jobs:
  build-core:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo/core
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: |
            npm test -- --reporter mocha-junit-reporter

          environment:
            MOCHA_FILE: ./junit/core-test-results.xml

      - store_artifacts:
          path: ./junit/core-test-results.xml
          prefix: core

      - store_test_results:
          path: ./junit

  build-task-manager:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo/task-manager
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: |
            npm test -- --reporter mocha-junit-reporter

          environment:
            MOCHA_FILE: ./junit/task-manager-test-results.xml

      - store_artifacts:
          path: ./junit/task-manager-test-results.xml
          prefix: task-manager

      - store_test_results:
          path: ./junit
workflows:
  version: 2
  build-all:
    jobs:
      - build-core:
          filters:
            branches:
              ignore:
                - gh-pages
      - build-task-manager:
          filters:
            branches:
              ignore:
                - gh-pages
