version: 2
jobs:
  check-commit:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: check-commit
          command:
            - bash ./scripts/check-commit.sh

  build-core:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo/core
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: |
            npm test -- --reporter mocha-junit-reporter

          environment:
            MOCHA_FILE: ./junit/core-test-results.xml

      - store_artifacts:
          path: ./junit/core-test-results.xml
          prefix: core

      - store_test_results:
          path: ./junit

  build-task-manager:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo/task-manager
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: |
            npm test -- --reporter mocha-junit-reporter

          environment:
            MOCHA_FILE: ./junit/task-manager-test-results.xml

      - store_artifacts:
          path: ./junit/task-manager-test-results.xml
          prefix: task-manager

      - store_test_results:
          path: ./junit

  build-crud-editor:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo/crud-editor
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: lint
          command: npm run lint-fix

      - run:
          name: build-gh-pages
          command: ./scripts/gh-pages/build.sh

      - run:
          name: deploy-gh-pages
          command: ./scripts/gh-pages/deploy.sh .gh-pages-tmp
workflows:
  version: 2
  build-all:
    jobs:
      - check-commit:
          filters:
            branches:
              ignore:
                - gh-pages
