version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: save-cache-checksum
          command: find -name "package.json" | xargs cat > /tmp/cache-checksum

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/tmp/cache-checksum" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: bootstrap (install dependencies)
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "/tmp/cache-checksum" }}
          paths:
            - node_modules
            - packages/core/node_modules
            - packages/history/node_modules
            - packages/task-manager/node_modules

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: |
            npm test

      - store_artifacts:
          path: ./packages/core/test-results.xml
          prefix: core

      - store_artifacts:
          path: ./packages/task-manager/test-results.xml
          prefix: task-manager

      - store_artifacts:
          path: ./packages/history/test-results.xml
          prefix: history

      - store_artifacts:
          path: ./packages/editor/test-results.xml
          prefix: editor

      - store_test_results:
          path: ./junit

  build-editor:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo/packages/editor
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: lint
          command: npm run lint-fix
      - run:
          name: lint
          command: npm run test
      - run:
          name: build-gh-pages
          command: bash ./scripts/gh-pages/build.sh
      - run:
          name: deploy-gh-pages
          command: bash ./scripts/gh-pages/deploy.sh .gh-pages-tmp-editor

workflows:
  version: 2
  build-all:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - build-editor:
          filters:
            branches:
              ignore:
                - gh-pages
