{{- $serviceName := include "fsm-workflow.fullname" . -}}
{{- $path := .Values.ingress.path -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fsm-workflow.fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "labels" . | indent 6 }}
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{ include "labels" . | indent 8 }}
      annotations:
        date: {{ now }} # RollingRestart workaround. https://github.com/kubernetes/kubernetes/issues/13488
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3020
          name: app
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: {{ $path }}
            port: 3020
          periodSeconds: 3
          timeoutSeconds: 240            
      imagePullSecrets:
        - name: {{.Values.dockerSecret}}
