apiVersion: v1
kind: Service
metadata:
  name: {{ template "fsm-workflow.fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3020
  selector:
{{ include "labels" . | indent 4 }}
