ingress:
  hosts:
  - "${MINSK_CORE_K8S_DEMO_DEPLOYMENTS_HOST}"
  path: "${APPLICATION_URL_PATH}"
image:
  repository: "${DOCKER_IMAGE_REPOSITORY}"
  tag: "${DOCKER_IMAGE_TAG}"
github-status-deployment-link:
  github:
    user: "${GH_NAME}"
    password: "${GH_PASS}"
    project: "${GITHUB_PROJECT}"
    ref: "${COMMIT}"
  url: "${APPLICATION_URL}"
selfkiller:
  azureAks:
    resourceGroup: "${MINSK_CORE_K8S_AZURE_RG}"
    clusterName: "${MINSK_CORE_K8S_AZURE_NAME}"
  image:
    repository: "${DOCKER_IMAGE_REPOSITORY}"
    tag: "${DOCKER_IMAGE_TAG}"
  github:
    project: "${GITHUB_PROJECT}"
    branch: "${BRANCH}"
slack-notifications:
  webhook: "${MINSK_CORE_SLACK_CI_WEBHOOK_URL}"
  github:
    user: "${CIRCLE_USERNAME}"
    project: "${GITHUB_PROJECT}"
    branch: "${BRANCH}"
    ref: "${COMMIT}"
  ci:
    jobUrl: "${CIRCLE_BUILD_URL}"
  link:
    url: "${APPLICATION_URL}"
dockerSecret: "${IMAGE_PULL_SECRET_NAME}"
